import { expect, afterEach, vi } from 'vitest';
import { cleanup } from '@testing-library/react';
import * as matchers from '@testing-library/jest-dom/matchers';
import { mockAnimationsApi } from 'jsdom-testing-mocks';

// Mock animations API for Headless UI
mockAnimationsApi();

// Extend Vitest's expect with jest-dom matchers
expect.extend(matchers);

// Cleanup after each test
afterEach(() => {
  cleanup();
});

// Mock AWS Amplify
vi.mock('aws-amplify', () => ({
  Amplify: {
    configure: vi.fn(),
  },
}));

// Mock Amplify UI React
vi.mock('@aws-amplify/ui-react', () => ({
  useAuthenticator: vi.fn(() => ({
    authStatus: 'authenticated',
    user: { username: 'test-user' },
    signOut: vi.fn(),
  })),
  Authenticator: ({ children }: { children: React.ReactNode }) => children,
}));

// Mock window.matchMedia
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: vi.fn().mockImplementation((query) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: vi.fn(),
    removeListener: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    dispatchEvent: vi.fn(),
  })),
});

// Mock ResizeObserver for Headless UI dropdowns
global.ResizeObserver = class ResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
};

// Mock scrollIntoView for jsdom
Element.prototype.scrollIntoView = vi.fn();

// Mock URL.createObjectURL/revokeObjectURL for jsdom (used by image previews
// in EquipmentImageUploadDialog).
if (!URL.createObjectURL) {
  URL.createObjectURL = vi.fn(() => 'blob:mock');
}
if (!URL.revokeObjectURL) {
  URL.revokeObjectURL = vi.fn();
}

// Mock window.alert
global.alert = vi.fn();

// Mock react-i18next with actual translations
vi.mock('react-i18next', () => {
  const translations = {
    'app.loading': 'Loading...',
    'app.name': 'Dispatch',
    'auth.signInPrompt': 'Sign in to your account',
    'common.actions.add': 'Add {{entity}}',
    'common.actions.addFirst': 'Add your first {{entity, lowercase}}',
    'common.actions.back': 'Back',
    'common.actions.backTo': 'Back to {{entities}}',
    'common.actions.create': 'Create {{entity}}',
    'common.actions.createFirst': 'Create your first {{entity, lowercase}}',
    'common.actions.deleteConfirm': 'Are you sure you want to delete {{name}}?',
    'common.actions.deleteConfirmGeneric': 'Are you sure you want to delete this {{entity, lowercase}}?',
    'common.actions.edit': 'Edit {{entity}}',
    'common.actions.errorLoading': 'Error loading {{entities, lowercase}}',
    'common.actions.errorLoadingEntity': 'Error loading {{entity, lowercase}}',
    'common.actions.loading': 'Loading {{entities, lowercase}}...',
    'common.actions.loadingEntity': 'Loading {{entity, lowercase}}...',
    'common.actions.new': 'New {{entity}}',
    'common.actions.noEntitiesYet': 'No {{entities, lowercase}} yet',
    'common.actions.noMatchSearch': 'No {{entities, lowercase}} match your search.',
    'common.actions.notFound': 'No {{entities, lowercase}} found',
    'common.actions.open': 'Open {{entities}}',
    'common.actions.removeFilter': 'Remove {{name}} filter',
    'common.active': 'Active',
    'common.add': 'Add',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.cloning': 'Cloning...',
    'common.create': 'Create',
    'common.delete': 'Delete',
    'common.deleting': 'Deleting...',
    'common.disabled': 'Disabled',
    'common.edit': 'Edit',
    'common.enabled': 'Enabled',
    'common.entitiesCount': '{{entities}} ({{count}})',
    'common.hide': 'Hide',
    'common.loading': 'Loading...',
    'common.moveDown': 'Move down',
    'common.moveUp': 'Move up',
    'common.recentEntities': 'Recent {{entities}}',
    'common.restoring': 'Restoring...',
    'common.search': 'Search...',
    'common.show': 'Show',
    'common.view': 'View',
    'common.viewAll': 'View all',
    'common.form.accessInstructions': 'Access Instructions',
    'common.form.address': 'Address',
    'common.form.addressLine2': 'Address Line 2',
    'common.form.billingAddress': 'Billing Address',
    'common.form.billingAddressSameAsService': 'Send invoice to same address',
    'common.form.city': 'City',
    'common.form.code': 'Code',
    'common.form.color': 'Color',
    'common.form.contractPricingTier': 'Contract Pricing Tier',
    'common.form.description': 'Description',
    'common.form.descriptionCreate': 'Create a new {{entity, lowercase}} record.',
    'common.form.descriptionEdit': 'Update {{entity, lowercase}} information.',
    'common.form.email': 'Email',
    'common.form.errorCreate': 'Failed to create {{entity, lowercase}}',
    'common.form.errorUpdate': 'Failed to update {{entity, lowercase}}',
    'common.form.firstName': 'First Name',
    'common.form.lastName': 'Last Name',
    'common.form.locationName': 'Location Name',
    'common.form.name': 'Name',
    'common.form.notes': 'Notes',
    'common.form.paymentTermsDays': 'Payment Terms (Days)',
    'common.form.phone': 'Phone',
    'common.form.requiresPurchaseOrder': 'Requires Purchase Order',
    'common.form.role': 'Role',
    'common.form.select': 'Select...',
    'common.form.serviceAddress': 'Service Address',
    'common.form.siteContactEmail': 'Site Contact Email',
    'common.form.siteContactName': 'Site Contact Name',
    'common.form.siteContactPhone': 'Site Contact Phone',
    'common.form.sortOrder': 'Sort Order',
    'common.form.state': 'State',
    'common.form.stateHelper': 'CA',
    'common.form.status': 'Status',
    'common.form.streetAddress': 'Street Address',
    'common.form.taxExempt': 'Tax Exempt',
    'common.form.taxExemptCertificate': 'Tax Exempt Certificate',
    'common.form.titleCreate': '{{action}} {{entity}}',
    'common.form.titleEdit': '{{action}} {{entity}}',
    'common.form.zipCode': 'Zip Code',
    'common.form.invalidEmail': 'Invalid email address',
    'common.form.errorDelete': 'Failed to delete {{entity, lowercase}}',
    'common.form.required': '{{field}} is required',
    'common.moreOptions': 'More options',
    'common.next': 'Next',
    'common.pagination.next': 'Next',
    'common.pagination.pageOf': 'Page {{page}} of {{total}}',
    'common.pagination.previous': 'Previous',
    'common.pagination.showing': 'Showing {{start}}-{{end}} of {{total}}',
    'common.previous': 'Previous',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'contacts.title': 'Additional Contacts',
    'contacts.entity': 'Additional Contact',
    'contacts.noContacts': 'No additional contacts yet',
    'contacts.actions.add': 'Add Additional Contact',
    'contacts.form.titleCreate': 'Create Additional Contact',
    'contacts.form.titleEdit': 'Edit Additional Contact',
    'contacts.form.descriptionCreate': 'Add a new contact for this location.',
    'contacts.form.descriptionEdit': 'Update contact information.',
    'contacts.delete.title': 'Delete Additional Contact',
    'contacts.delete.message': 'Are you sure you want to delete {{name}}?',
    'contacts.table.contact': 'Contact',
    'common.signOut': 'Sign out',
    'common.theme': 'Theme',
    'common.update': 'Update',
    'customers.description': 'Manage your customer database',
    'customers.displayMode.simple': 'Simple',
    'customers.displayMode.standard': 'Standard',
    'customers.detail.addEquipment': 'Add Equipment',
    'customers.detail.addLocation': 'Add Location',
    'customers.detail.addServiceLocation': 'Add Service Location',
    'customers.detail.addServiceLocationDescription': 'Add a new service location for this customer.',
    'customers.detail.balance': 'Balance',
    'customers.detail.backToCustomers': 'Back to Customers',
    'customers.detail.billingAddressLabel': 'Billing Address',
    'customers.detail.businessTerms': 'Business Terms',
    'customers.detail.businessTermsOptional': 'Business Terms (optional)',
    'customers.detail.contractTier': 'Contract Tier',
    'customers.detail.equipment': 'Equipment',
    'customers.detail.equipmentCount': 'Equipment: {{count}}',
    'customers.detail.errorLoading': 'Error loading customer',
    'customers.detail.lastService': 'Last Service',
    'customers.detail.lastServiceNever': 'Last service: Never',
    'customers.detail.netTerms': 'Net-{{days}}',
    'customers.detail.never': 'Never',
    'customers.detail.noEquipment': 'No equipment recorded yet',
    'customers.detail.noPhone': 'No phone',
    'customers.detail.noWorkOrders': 'No work orders yet',
    'customers.detail.openWorkOrders': 'Open Work Orders',
    'customers.detail.paymentTerms': 'Payment Terms (Days)',
    'customers.detail.recentWorkOrders': 'Recent Work Orders',
    'customers.detail.requiresPo': 'Requires PO',
    'customers.detail.serviceLocationsCount': 'Service Locations ({{count}})',
    'customers.detail.siteContact': 'Site Contact (optional)',
    'customers.detail.taxCert': 'Tax Cert #',
    'customers.detail.taxExemptBadge': 'Tax Exempt',
    'customers.detail.viewDetails': 'View Details →',
    'customers.form.accessInstructionsOptional': 'Access Instructions (optional)',
    'customers.form.billingAddressHelp': 'Check this if invoices should be sent to the service address',
    'customers.form.billingAddressSection': 'Billing Address',
    'customers.form.billingInvoiceRecipient': 'Invoice Recipient',
    'customers.form.businessDetails': 'Business Details',
    'customers.form.companyName': 'Company/Name *',
    'customers.form.locationNameHelp': 'Optional - useful for businesses with multiple locations',
    'customers.form.newWorkOrder': 'New Work Order',
    'customers.form.paymentTermsHelp': '0 = Due on receipt',
    'customers.form.serviceLocationPrompt': 'Where do you need service?',
    'customers.form.serviceLocationSection': 'Service Location',
    'customers.table.billingAddress': 'Billing Address',
    'customers.table.location': 'Location',
    'customers.table.locationAddress': 'Address',
    'customers.table.locationContact': 'Contact',
    'customers.table.locationName': 'Location Name',
    'customers.table.locations': 'Locations',
    'customers.table.locationsCount': '{{count}} locations',
    'customers.table.moreLocations': '+{{count}} more',
    'customers.table.none': 'None',
    'customers.table.terms': 'Terms',
    'customers.table.type': 'Type',
    'customers.tabs.activity': 'Activity',
    'customers.tabs.financial': 'Financial',
    'customers.tabs.overview': 'Overview',
    'dashboard.stats.activeWorkOrders': 'Active work orders',
    'dashboard.stats.thisMonth': 'This month',
    'dashboard.stats.totalCustomers': 'Total customers',
    'dashboard.welcome': 'Welcome to Dispatch',
    'entities.customer': 'Customer',
    'entities.customers': 'Customers',
    'entities.dashboard': 'Dashboard',
    'entities.dispatch': 'Dispatch',
    'entities.dispatches': 'Dispatches',
    'entities.division': 'Division',
    'entities.divisions': 'Divisions',
    'entities.equipment': 'Equipment',
    'entities.equipmentComponent': 'Unit',
    'entities.equipmentComponents': 'Units',
    'entities.financial': 'Financial',
    'entities.inventory': 'Inventory',
    'entities.invoice': 'Invoice',
    'entities.invoices': 'Invoices',
    'entities.payment': 'Payment',
    'entities.payments': 'Payments',
    'entities.quote': 'Quote',
    'entities.quotes': 'Quotes',
    'entities.region': 'Region',
    'entities.regions': 'Regions',
    'entities.revenue': 'Revenue',
    'entities.role': 'Role',
    'entities.roles': 'Roles',
    'entities.scheduling': 'Scheduling',
    'entities.serviceLocation': 'Service Location',
    'entities.serviceLocations': 'Service Locations',
    'entities.settings': 'Settings',
    'entities.tenantSettings': 'Tenant Settings',
    'entities.user': 'User',
    'entities.users': 'Users',
    'entities.workOrder': 'Work Order',
    'entities.workOrders': 'Work Orders',
    'equipment.comingSoon': 'Coming soon...',
    'equipment.description': 'Track equipment and inventory',
    'equipment.descriptionParts': 'Manage parts inventory across warehouses',
    'equipment.descriptionWarehouses': 'Manage warehouse locations and inventory storage',
    'equipment.detail.breadcrumbAriaLabel': '{{entity}} location',
    'equipment.detail.created': 'Created',
    'equipment.detail.descriptionPlaceholder': 'Add a description…',
    'equipment.detail.identification': 'Identification',
    'equipment.detail.lastServiced': 'Last Serviced',
    'equipment.detail.lifecycle': 'Lifecycle',
    'equipment.detail.noProfileImage': 'No profile image',
    'equipment.detail.profileImageAlt': '{{name}} profile image',
    'equipment.detail.tabComingSoon': 'Coming soon.',
    'equipment.images.addCaption': 'Add caption',
    'equipment.images.addPhoto': 'Add Photo',
    'equipment.images.batchEmpty': 'Choose one or more photos to add.',
    'equipment.images.captionPlaceholder': 'e.g. Nameplate, Compressor model number',
    'equipment.images.chooseFile': 'Choose file',
    'equipment.images.deleteConfirm': 'Delete this photo?',
    'equipment.images.dropHereActive': 'Drop to add',
    'equipment.images.dropOrChoose': 'Drag photos here, or',
    'equipment.images.editCaption': 'Edit caption',
    'equipment.images.empty': 'No photos added yet.',
    'equipment.images.errorCreate': 'Failed to upload photo',
    'equipment.images.errorDelete': 'Failed to delete photo',
    'equipment.images.errorLoading': 'Failed to load photos',
    'equipment.images.errorUpdate': 'Failed to update photo',
    'equipment.images.fileRequired': 'Choose a photo to upload.',
    'equipment.images.headingWithCount': 'Photos ({{count}})',
    'equipment.images.lightboxPosition': '{{current}} of {{total}}',
    'equipment.images.limitReached': 'This {{entity, lowercase}} already has the maximum {{max}} photos.',
    'equipment.images.loading': 'Loading photos…',
    'equipment.images.manage': 'Manage',
    'equipment.images.newCaption': 'New caption',
    'equipment.images.noFileChosen': 'No file chosen',
    'equipment.images.openFullSize': 'Open full-size in a new tab',
    'equipment.images.profile': 'Profile',
    'equipment.images.removeFromBatch': 'Remove from batch',
    'equipment.images.rowDone': 'Uploaded',
    'equipment.images.setAsProfile': 'Set as profile',
    'equipment.images.stageConfirming': 'Processing…',
    'equipment.images.stageRequesting': 'Preparing upload…',
    'equipment.images.stageUploading': 'Uploading…',
    'equipment.images.titleAdd': 'Add Photo',
    'equipment.images.titleEditCaption': 'Edit Caption',
    'equipment.images.tooLarge': 'File is {{size}} MB; the maximum is {{max}} MB.',
    'equipment.images.unsupportedType': 'Only JPEG, PNG, and WEBP are supported. HEIC photos must be converted before upload.',
    'equipment.images.uploadCount': 'Upload {{count}} photos',
    'equipment.notes.addNote': 'Add note',
    'equipment.notes.composerLabel': 'Note body',
    'equipment.notes.composerPlaceholder': 'Replaced compressor...',
    'equipment.notes.deleteConfirm': 'Delete this note?',
    'equipment.notes.editHint': 'Cmd/Ctrl+Enter to save · Esc to cancel',
    'equipment.notes.editHover': 'Click to edit',
    'equipment.notes.errorCreate': 'Failed to add note',
    'equipment.notes.errorDelete': 'Failed to delete note',
    'equipment.notes.errorUpdate': 'Failed to update note',
    'equipment.notes.heading': 'Notes',
    'equipment.notes.headingWithCount': 'Notes ({{count}})',
    'equipment.notes.helper': 'Saved with this equipment, not this work order',
    'equipment.notes.systemAuthor': 'System',
    'equipment.notes.viewAll': '{{count}} more on the equipment page',
    'equipment.tabs.photos': 'Photos',
    'equipment.filters.addFilter': 'Add Filter',
    'equipment.filters.deleteConfirm': 'Delete this filter?',
    'equipment.filters.empty': 'No filters added yet.',
    'equipment.filters.errorCreate': 'Failed to add filter',
    'equipment.filters.errorDelete': 'Failed to delete filter',
    'equipment.filters.errorLoading': 'Failed to load filters',
    'equipment.filters.errorUpdate': 'Failed to update filter',
    'equipment.filters.invalidDimensions': 'Length, width, and thickness must all be greater than zero.',
    'equipment.filters.invalidQuantity': 'Quantity must be a whole number of 1 or more.',
    'equipment.filters.label': 'Label',
    'equipment.filters.labelPlaceholder': 'e.g. Return air, Pre-filter',
    'equipment.filters.length': 'Length (in)',
    'equipment.filters.loading': 'Loading filters…',
    'equipment.filters.quantity': 'Quantity',
    'equipment.filters.quickAdd': 'Quick add',
    'equipment.filters.showAll': 'Show all ({{count}})',
    'equipment.filters.showFewer': 'Show fewer',
    'equipment.filters.size': 'Size',
    'equipment.filters.thickness': 'Thickness (in)',
    'equipment.filters.titleAdd': 'Add Filter',
    'equipment.filters.titleEdit': 'Edit Filter',
    'equipment.filters.width': 'Width (in)',
    'equipment.lowStock': 'Low Stock',
    'equipment.entities.part': 'Part',
    'equipment.entities.parts': 'Parts',
    'equipment.entities.warehouse': 'Warehouse',
    'equipment.entities.warehouses': 'Warehouses',
    'equipment.filter.allCategories': 'All Categories',
    'equipment.filter.allTypes': 'All Types',
    'equipment.picker.clear': 'Clear selection',
    'equipment.picker.createNew': '+ Create new {{entity, lowercase}} "{{name}}"',
    'equipment.picker.noResults': 'No {{entity, lowercase}} found at this location.',
    'equipment.picker.placeholder': 'Search by name, serial, model…',
    'equipment.picker.quickCreateHint': 'Other details can be filled in later from the {{entity, lowercase}} page.',
    'equipment.form.assetTag': 'Asset Tag',
    'equipment.form.category': 'Category',
    'equipment.form.customer': 'Customer',
    'equipment.form.equipmentType': 'Equipment Type',
    'equipment.form.installDate': 'Install Date',
    'equipment.form.locationBin': 'Bin Location',
    'equipment.form.location': 'Location',
    'equipment.form.locationOnSite': 'Location on Site',
    'equipment.form.make': 'Make',
    'equipment.form.manager': 'Manager Name',
    'equipment.form.model': 'Model',
    'equipment.form.modelNumber': 'Model Number',
    'equipment.form.partName': 'Part Name',
    'equipment.form.partNumber': 'Part Number',
    'equipment.form.quantityOnHand': 'Quantity On Hand',
    'equipment.form.reorderPoint': 'Reorder Point',
    'equipment.form.reorderQuantity': 'Reorder Quantity',
    'equipment.form.serialNumber': 'Serial Number',
    'equipment.form.serviceLocation': 'Service Location',
    'equipment.form.titleAddSubUnit': 'Add {{entity}} to {{parent}}',
    'equipment.form.type': 'Type',
    'equipment.form.unitCost': 'Unit Cost',
    'equipment.form.warehouse': 'Warehouse',
    'equipment.form.warrantyDetails': 'Warranty Details',
    'equipment.form.warrantyExpiresAt': 'Warranty Expires',
    'equipment.status.active': 'Active',
    'equipment.status.all': 'All',
    'equipment.status.retired': 'Retired',
    'equipment.tabs.filters': 'Filters',
    'equipment.tabs.notes': 'Notes',
    'equipment.tabs.overview': 'Overview',
    'equipment.tabs.serviceHistory': 'Service History',
    'equipment.table.category': 'Category',
    'equipment.table.componentOf': '{{entity}} of {{parent}}',
    'equipment.table.lastServiced': 'Last Serviced',
    'equipment.table.makeModel': 'Make · Model',
    'equipment.table.name': 'Name',
    'equipment.table.partNumber': 'Part #',
    'equipment.table.partName': 'Part Name',
    'equipment.table.quantity': 'Quantity',
    'equipment.table.reorderPoint': 'Reorder Point',
    'equipment.table.type': 'Type',
    'equipment.table.unitCost': 'Unit Cost',
    'equipment.table.warehouse': 'Warehouse',
    'financial.comingSoon': 'Coming soon...',
    'financial.description': 'Manage invoices, quotes, and payments',
    'invoices.description': 'Manage customer invoices and billing',
    'notifications.description': 'View notification history and manage preferences',
    'notifications.logs.errorLoad': 'Failed to load notification logs',
    'notifications.logs.filters.allChannels': 'All Channels',
    'notifications.logs.filters.allStatuses': 'All Statuses',
    'notifications.logs.loading': 'Loading notification logs...',
    'notifications.logs.noLogs': 'No notification logs found',
    'notifications.logs.pagination.next': 'Next',
    'notifications.logs.pagination.page': 'Page {{current}} of {{total}}',
    'notifications.logs.pagination.previous': 'Previous',
    'notifications.logs.pagination.showing': 'Showing {{start}}-{{end}} of {{total}}',
    'notifications.logs.status.bounced': 'Bounced',
    'notifications.logs.status.delivered': 'Delivered',
    'notifications.logs.status.failed': 'Failed',
    'notifications.logs.status.pending': 'Pending',
    'notifications.logs.status.sent': 'Sent',
    'notifications.logs.table.channel': 'Channel',
    'notifications.logs.table.delivered': 'Delivered',
    'notifications.logs.table.recipient': 'Recipient',
    'notifications.logs.table.sent': 'Sent',
    'notifications.logs.table.status': 'Status',
    'notifications.logs.table.type': 'Type',
    'notifications.logs.title': 'Notification History',
    'notifications.preferences.channelEmail': 'Email',
    'notifications.preferences.channelPush': 'Push',
    'notifications.preferences.channelSms': 'SMS',
    'notifications.preferences.description': 'Manage notification preferences for {{name}}',
    'notifications.preferences.errorLoad': 'Failed to load notification preferences',
    'notifications.preferences.errorUpdate': 'Failed to update notification preference',
    'notifications.preferences.formDescription': 'Choose which notifications this contact should receive',
    'notifications.preferences.manage': 'Manage Notifications',
    'notifications.preferences.noPreferences': 'No notification preferences available',
    'notifications.preferences.notificationType': 'Notification Type',
    'notifications.preferences.title': 'Notification Preferences',
    'payments.description': 'Track customer payments and transactions',
    'quotes.description': 'Create and manage customer quotes',
    'reports.backToReports': 'Back to Reports',
    'reports.description': 'Operational, financial, and equipment reports.',
    'reports.empty': 'No reports are available yet.',
    'reports.errorLoading': 'Error loading report',
    'reports.filterPullList.date': 'Date',
    'reports.filterPullList.description': 'Filter sizes and quantities needed for scheduled work orders.',
    'reports.filterPullList.empty': 'No filters needed for {{date}}.',
    'reports.filterPullList.equipmentCount': 'Equipment',
    'reports.filterPullList.from': 'From',
    'reports.filterPullList.mode': 'Date mode',
    'reports.filterPullList.mode_range': 'Range',
    'reports.filterPullList.mode_single': 'Single day',
    'reports.filterPullList.printContext': 'For scheduled work on {{date}}',
    'reports.filterPullList.quantity': 'Quantity',
    'reports.filterPullList.size': 'Size',
    'reports.filterPullList.title': 'Filter Pull List',
    'reports.filterPullList.to': 'To',
    'reports.filterPullList.total': 'Total filters: {{count}}',
    'reports.loading': 'Loading report…',
    'reports.notFound': 'That report does not exist.',
    'reports.print': 'Print',
    'reports.title': 'Reports',
    'reports.uncategorized': 'Other',
    'settings.equipmentCategories.add': 'Add Category',
    'settings.equipmentCategories.description': 'Sub-types within an equipment type.',
    'settings.equipmentCategories.empty': 'No categories yet for this type.',
    'settings.equipmentCategories.errorDelete': 'Failed to delete category',
    'settings.equipmentCategories.errorLoad': 'Failed to load categories',
    'settings.equipmentCategories.errorReorder': 'Failed to reorder categories',
    'settings.equipmentCategories.errorSave': 'Failed to save category',
    'settings.equipmentCategories.loading': 'Loading categories…',
    'settings.equipmentCategories.noTypesYet': 'Add at least one Equipment Type before creating categories.',
    'settings.equipmentCategories.parentType': 'Equipment Type',
    'settings.equipmentCategories.title': 'Equipment Categories',
    'settings.equipmentCategories.titleAdd': 'Add Category',
    'settings.equipmentCategories.titleEdit': 'Edit Category',
    'settings.equipmentTypes.add': 'Add Type',
    'settings.equipmentTypes.description': 'Top-level equipment classifications.',
    'settings.equipmentTypes.empty': 'No equipment types yet.',
    'settings.equipmentTypes.errorDelete': 'Failed to delete equipment type',
    'settings.equipmentTypes.errorLoad': 'Failed to load equipment types',
    'settings.equipmentTypes.errorReorder': 'Failed to reorder equipment types',
    'settings.equipmentTypes.errorSave': 'Failed to save equipment type',
    'settings.equipmentTypes.loading': 'Loading equipment types…',
    'settings.equipmentTypes.title': 'Equipment Types',
    'settings.equipmentTypes.titleAdd': 'Add Equipment Type',
    'settings.equipmentTypes.titleEdit': 'Edit Equipment Type',
    'settings.filterSizes.add': 'Add Size',
    'settings.filterSizes.description': 'Common filter sizes that appear as quick-add chips.',
    'settings.filterSizes.empty': 'No filter sizes configured yet.',
    'settings.filterSizes.errorDelete': 'Failed to delete filter size',
    'settings.filterSizes.errorLoad': 'Failed to load filter sizes',
    'settings.filterSizes.errorReorder': 'Failed to reorder filter sizes',
    'settings.filterSizes.errorSave': 'Failed to save filter size',
    'settings.filterSizes.errorSeed': 'Failed to seed common filter sizes',
    'settings.filterSizes.invalidDimensions': 'Length, width, and thickness must all be greater than zero.',
    'settings.filterSizes.length': 'Length (in)',
    'settings.filterSizes.loading': 'Loading filter sizes…',
    'settings.filterSizes.seedCommon': 'Seed common',
    'settings.filterSizes.seedCommonCta': 'Seed common sizes (10)',
    'settings.filterSizes.seedCommonHelp': 'Add the 10 most-common HVAC residential filter sizes. Skips any already in your list.',
    'settings.filterSizes.seedResult': 'Added {{added}}, skipped {{skipped}}.',
    'settings.filterSizes.size': 'Size',
    'settings.filterSizes.thickness': 'Thickness (in)',
    'settings.filterSizes.title': 'Common Filter Sizes',
    'settings.filterSizes.titleAdd': 'Add Filter Size',
    'settings.filterSizes.titleEdit': 'Edit Filter Size',
    'settings.filterSizes.width': 'Width (in)',
    'scheduling.comingSoon': 'Coming soon...',
    'scheduling.description': 'Manage dispatches and technician schedules',
    'scheduling.descriptionDispatches': 'Schedule and manage work order dispatches',
    'scheduling.descriptionAvailability': 'Manage user availability schedules',
    'scheduling.descriptionRecurringOrders': 'Manage recurring maintenance schedules',
    'scheduling.entities.dispatch': 'Dispatch',
    'scheduling.entities.dispatches': 'Dispatches',
    'scheduling.entities.availability': 'Availability',
    'scheduling.entities.availabilityRecord': 'Availability Record',
    'scheduling.entities.recurringOrder': 'Recurring Order',
    'scheduling.entities.recurringOrders': 'Recurring Orders',
    'scheduling.form.assignedUser': 'Assigned User',
    'scheduling.form.customer': 'Customer',
    'scheduling.form.date': 'Date',
    'scheduling.form.endTime': 'End Time',
    'scheduling.form.equipment': 'Equipment',
    'scheduling.form.estimatedDuration': 'Estimated Duration (minutes)',
    'scheduling.form.frequency': 'Frequency',
    'scheduling.form.nextScheduledDate': 'Next Scheduled Date',
    'scheduling.form.reason': 'Reason',
    'scheduling.form.scheduledDate': 'Scheduled Date',
    'scheduling.form.startTime': 'Start Time',
    'scheduling.form.user': 'User',
    'scheduling.form.workOrder': 'Work Order',
    'scheduling.frequency.annually': 'Annually',
    'scheduling.frequency.monthly': 'Monthly',
    'scheduling.frequency.quarterly': 'Quarterly',
    'scheduling.frequency.weekly': 'Weekly',
    'serviceLocations.actions.close': 'Close Location',
    'serviceLocations.actions.closeConfirm': 'Are you sure you want to close {{name}}? This location will no longer be available for new work orders.',
    'serviceLocations.description': 'Manage service locations across all customers',
    'serviceLocations.detail.addEquipment': 'Add Equipment',
    'serviceLocations.detail.address': 'Address',
    'serviceLocations.detail.backToList': 'Back to Service Locations',
    'serviceLocations.detail.belongsTo': 'Belongs to',
    'serviceLocations.detail.businessLocation': 'Business',
    'serviceLocations.detail.created': 'Created',
    'serviceLocations.detail.equipment': 'Equipment',
    'serviceLocations.detail.errorLoading': 'Error loading service location',
    'serviceLocations.detail.lastService': 'Last Service',
    'serviceLocations.detail.lastUpdated': 'Last Updated',
    'serviceLocations.detail.loading': 'Loading service location...',
    'serviceLocations.detail.locationId': 'Location ID',
    'serviceLocations.detail.never': 'Never',
    'serviceLocations.detail.newWorkOrder': 'New Work Order',
    'serviceLocations.detail.noEquipment': 'No equipment recorded yet',
    'serviceLocations.detail.noWorkOrders': 'No work orders yet',
    'serviceLocations.detail.openWorkOrders': 'Open Work Orders',
    'serviceLocations.detail.quickStats': 'Quick Stats',
    'serviceLocations.detail.recentWorkOrders': 'Recent Work Orders',
    'serviceLocations.detail.siteContact': 'Site Contact',
    'serviceLocations.detail.systemInfo': 'System Information',
    'serviceLocations.detail.totalEquipment': 'Total Equipment',
    'serviceLocations.detail.totalRevenue': 'Total Revenue',
    'serviceLocations.detail.unnamedLocation': 'Unnamed Location',
    'serviceLocations.detail.uspsValidated': 'USPS Validated',
    'serviceLocations.filter.allRegions': 'All regions',
    'serviceLocations.filter.allStatuses': 'All statuses',
    'serviceLocations.filter.region': 'Region',
    'serviceLocations.status.active': 'Active',
    'serviceLocations.status.closed': 'Closed',
    'serviceLocations.status.inactive': 'Inactive',
    'serviceLocations.table.address': 'Address',
    'serviceLocations.table.contact': 'Contact',
    'serviceLocations.table.customer': 'Customer',
    'serviceLocations.table.equipment': 'Equipment',
    'serviceLocations.table.lastService': 'Last Service',
    'serviceLocations.table.locationName': 'Location Name',
    'serviceLocations.table.neverServiced': 'Never',
    'serviceLocations.table.type': 'Type',
    'serviceLocations.tabs.activity': 'Activity',
    'serviceLocations.tabs.overview': 'Overview',
    'users.actions.deleteWarning': 'This action cannot be undone. All user data and history will be permanently removed.',
    'users.actions.disableConfirm': 'Are you sure you want to disable {{name}}? They will no longer be able to log in.',
    'users.actions.enableConfirm': 'Are you sure you want to enable {{name}}?',
    'users.description': 'Manage user accounts and permissions',
    'users.detail.activityComingSoon': 'Activity history coming soon',
    'users.detail.activityHelper': 'Will show login history, actions performed, etc.',
    'users.detail.auditComingSoon': 'Audit trail coming soon',
    'users.detail.auditHelper': 'Will show permission changes, profile updates, etc.',
    'users.detail.basicInfo': 'Basic Information',
    'users.detail.capabilities': 'Capabilities',
    'users.detail.cognitoSub': 'Cognito Sub',
    'users.detail.created': 'Created',
    'users.detail.lastUpdated': 'Last Updated',
    'users.detail.noCapabilities': 'No capabilities assigned',
    'users.detail.noRegionsAssigned': 'No regions assigned',
    'users.detail.recentActivity': 'Recent Activity',
    'users.detail.rolePermissions': 'Role & Permissions',
    'users.detail.showLess': 'Show less',
    'users.detail.showMore': 'Show {{count}} more...',
    'users.detail.systemInfo': 'System Information',
    'users.detail.userId': 'User ID',
    'users.filter.all': 'All',
    'users.filter.allRoles': 'All roles',
    'users.filter.clearFilters': 'Clear filters',
    'users.filter.disabled': 'Disabled',
    'users.filter.enabled': 'Enabled',
    'users.filter.role': 'Role',
    'users.filter.status': 'Status',
    'users.form.adminRoleInfo': 'Admin role includes all permissions. Other roles are not needed.',
    'users.form.assignedRegions': 'Assigned Regions',
    'users.form.rolePlaceholder': 'Select a role...',
    'users.form.roleRequired': 'Please select at least one role',
    'users.form.sendInvite': 'Send invitation email',
    'users.search.noMatch': 'No users match "{{query}}"',
    'users.search.placeholder': 'Search by name, email, or role...',
    'users.status.disabled': 'Disabled',
    'users.status.enabled': 'Enabled',
    'users.table.actions': 'Actions',
    'users.table.auditLog': 'Audit Log',
    'users.table.disable': 'Disable',
    'users.table.enable': 'Enable',
    'users.table.lastUpdated': 'Last Updated',
    'capabilities.clearGroup': 'Clear group',
    'capabilities.collapseAll': 'Collapse All',
    'capabilities.description': 'Select the capabilities this role should have. Users assigned this role will inherit these permissions.',
    'capabilities.errorLoading': 'Error loading capabilities',
    'capabilities.expandAll': 'Expand All',
    'capabilities.label': 'Capabilities',
    'capabilities.noCapabilities': 'No capabilities assigned',
    'capabilities.selectedLower': 'selected',
    'capabilities.totalCount': 'capabilities',
    'capabilities.unknownError': 'Unknown error',
    'roles.actions.clone': 'Clone Role',
    'roles.actions.cloneDescription': 'Create a copy of "{{name}}" with all its capabilities.',
    'roles.actions.deleteWarning': 'This action cannot be undone. Users assigned this role will lose associated capabilities.',
    'roles.actions.errorClone': 'Failed to clone role',
    'roles.actions.errorRestoreAll': 'Failed to restore default roles',
    'roles.actions.restore': 'Restore',
    'roles.actions.restoreAllDefaults': 'Restore All Defaults',
    'roles.actions.restoreAllDefaultsConfirm': 'Restore All Default Roles?',
    'roles.actions.restoreAllDefaultsDescription': 'This will reset all {{count}} default system roles to their original state.',
    'roles.actions.restoreAllDefaultsDetails': 'What will happen: Modified system roles will be reset (names and capabilities). Deleted system roles will be recreated. Custom roles you\'ve created will be preserved. User assignments will be preserved.',
    'roles.actions.restoreAllDefaultsSuccess': 'Default roles restored successfully',
    'roles.actions.restoreAllDefaultsWarning': '⚠️ Any changes you\'ve made to default roles will be lost',
    'roles.actions.restoreDefaults': 'Restore Defaults',
    'roles.actions.restoreDefaultsConfirm': 'Restore "{{name}}" to default capabilities?',
    'roles.actions.restoreDefaultsWarning': 'This will reset all capabilities to the system template defaults. Custom changes will be lost.',
    'roles.description': 'Manage roles and their capabilities',
    'roles.restoreAllSummary.customRolesPreserved': '{{count}} custom role preserved',
    'roles.restoreAllSummary.rolesRecreated': '{{count}} role recreated',
    'roles.restoreAllSummary.rolesReset': '{{count}} role reset to defaults',
    'roles.restoreAllSummary.userAssignmentsPreserved': 'All user assignments have been preserved.',
    'roles.detail.created': 'Created',
    'roles.detail.lastUpdated': 'Last Updated',
    'roles.detail.roleId': 'Role ID',
    'roles.detail.roleInfo': 'Role Information',
    'roles.detail.systemInfo': 'System Information',
    'roles.detail.templateCode': 'Template Code',
    'roles.detail.totalCapabilities': 'Total Capabilities',
    'roles.form.descriptionCreate': 'Create a new role by defining its name, description, and capabilities.',
    'roles.form.descriptionEdit': 'Update role name, description, and capabilities.',
    'roles.table.capabilities': 'Capabilities',
    'roles.table.lastUpdated': 'Last Updated',
    'workOrders.actions.archive': 'Archive',
    'workOrders.actions.archiveConfirm': 'Archive this work order? It will be hidden from the default list.',
    'workOrders.actions.archived': 'Archived',
    'workOrders.actions.archiveError': 'Failed to archive work order',
    'workOrders.actions.cancel': 'Cancel Work Order',
    'workOrders.actions.cancelButton': 'Cancel work order',
    'workOrders.actions.cancelDescription': 'Cancelling marks this work order as no longer in scope. The reason is recorded and shown in the audit trail.',
    'workOrders.actions.cancelError': 'Failed to cancel work order',
    'workOrders.actions.cancelledBadge': 'Cancelled',
    'workOrders.actions.cancelReasonLabel': 'Reason for cancelling',
    'workOrders.actions.cancelReasonPlaceholder': 'e.g., Customer called to cancel',
    'workOrders.actions.cancelReasonRequired': 'A reason is required to cancel.',
    'workOrders.actions.cancelTitle': 'Cancel Work Order?',
    'workOrders.actions.charactersRemaining': '{{count}} characters remaining',
    'workOrders.actions.frozenHelper': 'This work order is cancelled and can no longer be edited.',
    'workOrders.actions.showArchived': 'Show archived',
    'workOrders.actions.unarchive': 'Unarchive',
    'workOrders.actions.unarchiveError': 'Failed to unarchive work order',
    'workOrders.description': 'Manage work orders and service requests',
    'workOrders.dates.any': 'Any time',
    'workOrders.dates.custom': 'Custom range…',
    'workOrders.dates.from': 'From',
    'workOrders.dates.last30': 'Last 30 days',
    'workOrders.dates.last7': 'Last 7 days',
    'workOrders.dates.thisMonth': 'This month',
    'workOrders.dates.thisWeek': 'This week',
    'workOrders.dates.to': 'To',
    'workOrders.dates.today': 'Today',
    'workOrders.dates.yesterday': 'Yesterday',
    'workOrders.filters.all': 'All',
    'workOrders.filters.any': 'Any {{entity, lowercase}}',
    'workOrders.filters.anyDivision': 'Any division',
    'workOrders.filters.anyItemStatus': 'Any item status',
    'workOrders.filters.anyRegion': 'Any region',
    'workOrders.filters.anyType': 'Any type',
    'workOrders.filters.blocked': 'Blocked',
    'workOrders.filters.cancelled': 'Cancelled',
    'workOrders.filters.clearAll': 'Clear all',
    'workOrders.filters.completed': 'Completed',
    'workOrders.filters.inProgress': 'In Progress',
    'workOrders.filters.itemStatus': 'Item status',
    'workOrders.filters.notStarted': 'Not Started',
    'workOrders.filters.open': 'Open',
    'workOrders.filters.region': 'Region',
    'workOrders.filters.scheduled': 'Scheduled',
    'workOrders.filters.searchPlaceholder': 'Search by WO#, customer, phone, address…',
    'workOrders.form.customerOrderNumber': 'Customer PO',
    'workOrders.form.customerOrderNumberPlaceholder': 'e.g., PO-12345',
    'workOrders.form.customerPlaceholder': 'Select a customer...',
    'workOrders.form.customerRequired': 'Please select a customer',
    'workOrders.form.division': 'Division',
    'workOrders.form.divisionPlaceholder': 'Unassigned',
    'workOrders.form.existingCustomer': 'Existing customer',
    'workOrders.form.firstWorkItemDescription': 'First {{entity}} Description',
    'workOrders.form.firstWorkItemRequired': 'Please describe the first work item.',
    'workOrders.form.newCustomer': 'New customer',
    'workOrders.form.newCustomerDetails': 'New Customer Details',
    'workOrders.form.notToExceed': 'NTE',
    'workOrders.form.notToExceedInvalid': 'NTE must be a non-negative number.',
    'workOrders.form.notToExceedPlaceholder': 'e.g., 1500.00',
    'workOrders.form.priority': 'Priority',
    'workOrders.form.progressLabel': 'Progress',
    'workOrders.form.progressHelper': 'Derived automatically from work item statuses.',
    'workOrders.form.scheduledDate': 'Scheduled Date',
    'workOrders.form.selectServiceLocation': 'Please select a service location',
    'workOrders.form.type': 'Type',
    'workOrders.form.typePlaceholder': 'Unassigned',
    'workOrders.priority.high': 'High',
    'workOrders.priority.low': 'Low',
    'workOrders.priority.normal': 'Normal',
    'workOrders.priority.urgent': 'Urgent',
    'workOrders.progress.blocked': 'Blocked',
    'workOrders.progress.cancelled': 'Cancelled',
    'workOrders.progress.completed': 'Completed',
    'workOrders.progress.inProgress': 'In Progress',
    'workOrders.progress.notStarted': 'Not Started',
    'workOrders.status.cancelled': 'Cancelled',
    'workOrders.status.completed': 'Completed',
    'workOrders.status.inProgress': 'In Progress',
    'workOrders.status.pending': 'Pending',
    'workOrders.status.scheduled': 'Scheduled',
    'workOrders.table.amount': 'Amount',
    'workOrders.table.cancelledOn': 'Cancelled on {{date}}',
    'workOrders.table.customerPO': 'Customer PO',
    'workOrders.table.id': 'ID',
    'workOrders.table.priority': 'Priority',
    'workOrders.table.scheduled': 'Scheduled',
    'workOrders.table.statusHeader': 'Status',
    'workOrders.table.type': 'Type',
    'workOrders.table.work': 'Work',
    'workOrders.table.workItemsMore': '+{{count}} more',
    'workOrders.dispatches.arrivedAt': 'Arrived {{time}}',
    'workOrders.dispatches.assign': 'Assign',
    'workOrders.dispatches.assignDescription': 'The window is the customer commitment; duration is optional.',
    'workOrders.dispatches.assignTechnician': 'Assign technician',
    'workOrders.dispatches.departedAt': 'Departed {{time}}',
    'workOrders.dispatches.empty': 'No {{entity, lowercase}} assigned yet.',
    'workOrders.dispatches.form.arrivalWindowEnd': 'Arrival Window End',
    'workOrders.dispatches.form.arrivalWindowStart': 'Arrival Window Start',
    'workOrders.dispatches.form.estimatedDurationOptional': 'Estimated Duration (optional, minutes)',
    'workOrders.dispatches.form.notifyNow': 'Send SMS to technician now',
    'workOrders.dispatches.form.notifyNowDescription': "Off by default — send manually from the row when you're ready to confirm.",
    'workOrders.dispatches.form.technician': 'Technician',
    'workOrders.dispatches.form.windowEndAfterStart': 'Window end must be after window start.',
    'workOrders.dispatches.markArrived': 'Mark arrived',
    'workOrders.dispatches.markCompleted': 'Mark completed',
    'workOrders.dispatches.notify': 'Notify',
    'workOrders.dispatches.notifyError': 'Failed to send notification',
    'workOrders.dispatches.notifyMissingPhone': 'Technician has no phone number on file. SMS will fail.',
    'workOrders.dispatches.notifySent': 'Notification sent.',
    'workOrders.dispatches.status.CANCELLED': 'Cancelled',
    'workOrders.dispatches.status.COMPLETED': 'Completed',
    'workOrders.dispatches.status.IN_PROGRESS': 'In Progress',
    'workOrders.dispatches.status.SCHEDULED': 'Scheduled',
    'workOrders.dispatches.statusUpdateError': 'Failed to update dispatch status',
    'workOrders.dispatches.table.duration': 'Duration',
    'workOrders.dispatches.table.status': 'Status',
    'workOrders.dispatches.table.tech': 'Technician',
    'workOrders.dispatches.table.window': 'Window',
    'workOrders.workItems.empty': 'No {{children, lowercase}} on this {{entity, lowercase}} yet.',
    'workOrders.workItems.frozenHelper': 'This work order is cancelled — item statuses are read-only.',
    'workOrders.workItems.qtyHeader': 'Qty',
    'workOrders.workItems.statusUpdateError': 'Failed to update item status',
    'workOrders.workItems.totalHeader': 'Total',
    'workOrders.workItems.unitHeader': 'Unit',
    'settings.divisions.description': 'Operating units used to organize {{divisions}} and route work.',
    'settings.itemStatuses.categoryHelper': 'How this status behaves in workflows and reports.',
    'settings.itemStatuses.description': 'Customize the lifecycle statuses that work items move through.',
    'settings.itemStatuses.isTerminalHelper': 'Terminal statuses end the work item; no further transitions are allowed.',
    'settings.itemStatuses.table.category': 'Category',
    'settings.itemStatuses.table.terminal': 'Terminal',
    'settings.nav.general': 'General',
    'settings.nav.itemStatuses': 'Item Statuses',
    'settings.nav.notificationTemplates': 'Notification Templates',
    'settings.nav.statusWorkflows': 'Status Workflows',
    'settings.nav.terminology': 'Terminology',
    'settings.nav.types': 'Types',
    'settings.nav.workflowConfig': 'Workflow Config',
    'settings.sections.access': 'Access',
    'settings.sections.dispatch': '{{dispatch}}',
    'settings.sections.organization': 'Organization',
    'settings.sections.workOrders': '{{workOrders}}',
    'settings.statusWorkflows.addRule': 'Add Transition',
    'settings.statusWorkflows.description': 'Define which status transitions are allowed.',
    'settings.statusWorkflows.empty': 'No transition rules defined.',
    'settings.statusWorkflows.from': 'From',
    'settings.statusWorkflows.to': 'To',
    'settings.taxonomy.codeHelper': 'Stable identifier. UPPERCASE_WITH_UNDERSCORES. Auto-generated from name.',
    'settings.taxonomy.codeImmutable': 'Code cannot be changed after creation.',
    'settings.taxonomy.deleteConfirm': 'Delete "{{name}}"? If referenced by existing records it will be marked inactive instead.',
    'settings.workflowConfig.boardTypeHelper': 'Choose how the dispatch board groups work.',
    'settings.workflowConfig.defaultStatusHelper': 'Starting status applied to newly created work items.',
    'settings.workflowConfig.defaultTypeHelper': 'Pre-selected on the create work order form.',
    'settings.workflowConfig.description': 'Tenant-wide rules that govern how work moves through the system.',
    'settings.workflowConfig.enforceHelper': 'When enabled, only transitions defined in Status Workflows are allowed.',
    'settings.workflowConfig.noneOption': 'None',
    'settings.workOrderTypes.description': 'Categories that classify {{workOrder}}s.',
    'settings.workOrderTypes.singular': 'Type',
    'tenantSettings.description': 'Manage company branding, contact information, and business settings',
    'tenantSettings.sections.branding': 'Branding & Logo',
    'tenantSettings.sections.businessSettings': 'Business Settings',
    'tenantSettings.sections.companyInfo': 'Company Information',
    'tenantSettings.sections.contactInfo': 'Contact Information',
    'tenantSettings.sections.featureFlags': 'Feature Flags',
    'tenantSettings.form.address': 'Address',
    'tenantSettings.form.city': 'City',
    'tenantSettings.form.companyName': 'Company Name',
    'tenantSettings.form.companyNameShort': 'Short Name',
    'tenantSettings.form.companyNameShortHelper': 'Optional - used in tight spaces',
    'tenantSettings.form.companySlogan': 'Company Slogan',
    'tenantSettings.form.companySloganHelper': 'Optional - tagline or motto',
    'tenantSettings.form.defaultTaxRate': 'Default Tax Rate',
    'tenantSettings.form.defaultTaxRateHelper': 'Enter as decimal (e.g., 0.0825 for 8.25%)',
    'tenantSettings.form.email': 'Email',
    'tenantSettings.form.enableEmailNotifications': 'Enable Email Notifications',
    'tenantSettings.form.enableOnlineBooking': 'Enable Online Booking',
    'tenantSettings.form.enableSmsNotifications': 'Enable SMS Notifications',
    'tenantSettings.form.fax': 'Fax',
    'tenantSettings.form.invoiceTerms': 'Invoice Terms',
    'tenantSettings.form.invoiceTermsHelper': 'e.g., Net 30, Due on receipt',
    'tenantSettings.form.logo': 'Company Logo',
    'tenantSettings.form.logoHelper': 'Square images (1:1 ratio) work best. Max 5MB. PNG or JPEG only.',
    'tenantSettings.form.phone': 'Phone',
    'tenantSettings.form.primaryColor': 'Primary Color',
    'tenantSettings.form.primaryColorHelper': 'Main brand color (hex code)',
    'tenantSettings.form.secondaryColor': 'Secondary Color',
    'tenantSettings.form.secondaryColorHelper': 'Accent color (hex code)',
    'tenantSettings.form.state': 'State',
    'tenantSettings.form.stateHelper': 'Two-letter code (e.g., CA)',
    'tenantSettings.form.streetAddress': 'Street Address',
    'tenantSettings.form.timezone': 'Timezone',
    'tenantSettings.form.timezoneHelper': 'Used for displaying dates and scheduling',
    'tenantSettings.form.uploadLogo': 'Upload Logo',
    'tenantSettings.form.zipCode': 'Zip Code',
    'tenantSettings.glossary.customizedCount': 'Customized entity names: {{count}} override',
    'tenantSettings.glossary.customizedCount_other': 'Customized entity names: {{count}} overrides',
    'tenantSettings.glossary.description': 'Customize how entity names appear throughout the application. Leave blank to use defaults.',
    'tenantSettings.glossary.emptyState': 'No custom terminology configured. Using default entity names.',
    'tenantSettings.glossary.entity': 'Entity',
    'tenantSettings.glossary.loadingEntities': 'Loading entity types...',
    'tenantSettings.glossary.pluralForm': 'Plural Form',
    'tenantSettings.glossary.resetToDefault': 'Reset to default',
    'tenantSettings.glossary.singularForm': 'Singular Form',
    'tenantSettings.messages.errorLoadingSettings': 'Error loading tenant settings',
    'tenantSettings.messages.errorUpdateSettings': 'Failed to update settings',
    'tenantSettings.messages.errorUploadLogo': 'Failed to upload logo',
    'tenantSettings.messages.fileSizeTooLarge': 'File size must be less than 5MB',
    'tenantSettings.messages.invalidFileType': 'Only PNG and JPEG files are supported',
    'tenantSettings.messages.loadingSettings': 'Loading settings...',
    'tenantSettings.messages.logoUploadedSuccess': 'Logo uploaded successfully',
    'tenantSettings.messages.settingsUpdatedSuccess': 'Settings updated successfully',
    'tenantSettings.sections.terminology': 'Terminology',
    'tenantSettings.tabs.general': 'General',
    'tenantSettings.tabs.terminology': 'Terminology',
    'workOrders.detail.actionPending': 'Available in a future phase',
    'workOrders.detail.addNote': 'Add Note',
    'workOrders.detail.completed': 'Completed',
    'workOrders.detail.copyAddress': 'Click to copy address',
    'workOrders.detail.copyPhone': 'Click to copy phone',
    'workOrders.detail.created': 'Created',
    'workOrders.detail.customerContact': 'Customer Contact',
    'workOrders.detail.duplicate': 'Duplicate',
    'workOrders.detail.eta': 'ETA {{date}}',
    'workOrders.detail.etaLabel': 'ETA',
    'workOrders.detail.notScheduled': 'Not scheduled',
    'workOrders.detail.siteContact': 'Site Contact',
    'workOrders.detail.frozen': 'Cancelled or archived — actions are disabled',
    'workOrders.detail.info': '{{entity}} Info',
    'workOrders.detail.lastUpdated': 'Updated {{time}}',
    'workOrders.detail.money.balance': 'Balance',
    'workOrders.detail.money.invoiced': 'Invoiced',
    'workOrders.detail.money.nte': 'NTE',
    'workOrders.detail.money.paid': 'Paid',
    'workOrders.detail.money.placeholder': '{{label}}: —',
    'workOrders.detail.money.quoted': 'Quoted',
    'workOrders.detail.print': 'Print',
    'workOrders.workItems.changeStatus': 'Change status (currently {{current}})',
    'workOrders.workItems.backToEntity': 'Back to {{entity}}',
    'workOrders.workItems.collapseRow': 'Hide details',
    'workOrders.workItems.deleteConfirm': 'Delete this {{entity, lowercase}}? This cannot be undone.',
    'workOrders.workItems.editAll': 'Edit all',
    'workOrders.workItems.expandRow': 'Show details',
    'workOrders.workItems.noEquipmentLinked': 'No {{entity, lowercase}} linked.',
    'workOrders.workItems.openPage': 'Open page',
    'workOrders.workItems.subUnits': '{{entities}} ({{count}}):',
    'workOrders.workItems.subUnitsMore': '+{{count}} more →',
    'workOrders.workItems.descriptionRequired': 'Description is required',
    'workOrders.workItems.editDescription': 'Edit description',
    'workOrders.workItems.lastUpdated': 'Last updated',
    'workOrders.activity.activeDispatches': 'Active {{entities}}',
    'workOrders.activity.byline': 'by {{actor}} · {{time}}',
    'workOrders.activity.composer.ariaLabel': 'Add a note to this work order',
    'workOrders.activity.composer.error': "Couldn't save note",
    'workOrders.activity.composer.hint': 'Press N to focus, Cmd+Enter to save',
    'workOrders.activity.composer.placeholder': 'Add a note…',
    'workOrders.activity.composer.save': 'Save',
    'workOrders.activity.composer.saving': 'Saving…',
    'workOrders.activity.day.thisWeek': 'This week',
    'workOrders.activity.day.today': 'Today',
    'workOrders.activity.day.yesterday': 'Yesterday',
    'workOrders.activity.empty': 'No activity yet.',
    'workOrders.activity.emptyForFilter': 'No matching events for this filter.',
    'workOrders.activity.errorLoading': "Couldn't load activity.",
    'workOrders.activity.fieldLabel.completedDate': 'Completed Date',
    'workOrders.activity.fieldLabel.customerOrderNumber': 'Customer PO',
    'workOrders.activity.fieldLabel.priority': 'Priority',
    'workOrders.activity.fieldLabel.scheduledDate': 'Scheduled Date',
    'workOrders.activity.fieldLabel.workOrderTypeId': 'Type',
    'workOrders.activity.filter.all': 'All',
    'workOrders.activity.filter.dispatches': 'Dispatches',
    'workOrders.activity.filter.financial': '$',
    'workOrders.activity.filter.notes': 'Notes',
    'workOrders.activity.filter.status': 'Status',
    'workOrders.activity.heading': 'Activity',
    'workOrders.activity.kind.dispatchAssigned': '{{entity}} assigned to {{techName}}',
    'workOrders.activity.kind.dispatchCancelled': '{{entity}} cancelled',
    'workOrders.activity.kind.invoiceIssued':
      '{{entity}} {{invoiceNumber}} issued for {{amount}}',
    'workOrders.activity.kind.invoicePaid': '{{entity}} {{invoiceNumber}} paid',
    'workOrders.activity.kind.noteAdded': '{{bodyExcerpt}}',
    'workOrders.activity.kind.noteDeleted': 'Note deleted: {{bodyExcerpt}}',
    'workOrders.activity.kind.paymentReceived': '{{entity}} received: {{amount}}',
    'workOrders.activity.kind.quoteAccepted': '{{entity}} {{quoteNumber}} accepted',
    'workOrders.activity.kind.quoteDeclined': '{{entity}} {{quoteNumber}} declined',
    'workOrders.activity.kind.quoteSent':
      '{{entity}} {{quoteNumber}} sent for {{amount}}',
    'workOrders.activity.kind.unknown': 'Unrecognized activity',
    'workOrders.activity.kind.workItemCreated': 'Added {{entity, lowercase}}',
    'workOrders.activity.kind.workItemDeleted': 'Removed {{entity, lowercase}}',
    'workOrders.activity.kind.workItemStatusChanged':
      'Status changed from {{fromStatusName}} to {{toStatusName}}',
    'workOrders.activity.kind.workItemUpdated': '{{entity}}: {{field}} changed',
    'workOrders.activity.kind.workOrderArchived': '{{entity}} archived',
    'workOrders.activity.kind.workOrderCancelled': '{{entity}} cancelled',
    'workOrders.activity.kind.workOrderCreated': '{{entity}} created',
    'workOrders.activity.kind.workOrderUnarchived': '{{entity}} unarchived',
    'workOrders.activity.kind.workOrderUpdated':
      '{{field}} changed from {{fromValue}} to {{toValue}}',
    'workOrders.activity.loadMore': 'Load more',
    'workOrders.activity.loading': 'Loading activity…',
    'workOrders.activity.systemActor': 'System',
  };

  return {
    useTranslation: () => ({
      t: (key: string, params?: Record<string, unknown>) => {
        let translation = translations[key as keyof typeof translations] || key;
        if (params) {
          Object.keys(params).forEach((param) => {
            const value = String(params[param]);
            // Handle {{param, lowercase}} format
            translation = translation.replace(`{{${param}, lowercase}}`, value.toLowerCase());
            // Handle {{param}} format
            translation = translation.replace(`{{${param}}}`, value);
          });
        }
        return translation;
      },
      i18n: {
        changeLanguage: () => new Promise(() => {}),
      },
    }),
    initReactI18next: {
      type: '3rdParty',
      init: () => {},
    },
  };
});

// Mock ThemeContext
vi.mock('../contexts/ThemeContext', () => ({
  useTheme: vi.fn(() => ({
    theme: 'light',
    setTheme: vi.fn(),
    resolvedTheme: 'light',
  })),
  ThemeProvider: ({ children }: { children: React.ReactNode }) => children,
}));

// Mock GlossaryContext
vi.mock('../contexts/GlossaryContext', async () => {
  // Re-import inside mock for proper module resolution
  const { GLOSSARY_DEFAULTS } = await import('../contexts/GlossaryContext');

  return {
    useGlossary: vi.fn(() => ({
      getName: (code: string, plural = false) => {
        const entry = GLOSSARY_DEFAULTS[code];
        return entry ? (plural ? entry.plural : entry.singular) : code;
      },
      updateGlossary: vi.fn(),
    })),
    GlossaryProvider: ({ children }: { children: React.ReactNode }) => children,
    GLOSSARY_DEFAULTS, // Re-export for other tests if needed
  };
});

// Mock useCurrentUser hook
vi.mock('../hooks/useCurrentUser', () => ({
  useCurrentUser: vi.fn(() => ({
    data: {
      id: 'test-user-id',
      email: 'test@example.com',
      firstName: 'Test',
      lastName: 'User',
      enabled: true,
      capabilities: [
        'VIEW_USERS',
        'INVITE_USERS',
        'EDIT_USERS',
        'DELETE_USERS',
        'VIEW_ROLES',
        'CREATE_ROLES',
        'EDIT_ROLES',
        'DELETE_ROLES',
        'VIEW_CUSTOMERS',
        'ADD_CUSTOMERS',
        'EDIT_CUSTOMERS',
        'ARCHIVE_CUSTOMERS',
        'VIEW_SERVICE_LOCATIONS',
        'ADD_SERVICE_LOCATIONS',
        'EDIT_SERVICE_LOCATIONS',
        'CLOSE_SERVICE_LOCATIONS',
        'VIEW_SETTINGS',
        'EDIT_SETTINGS',
        'VIEW_AUDIT_LOGS',
      ],
      roles: [],
    },
    isLoading: false,
    error: null,
  })),
  useHasCapability: vi.fn((capability: string) => {
    const capabilities = [
      'VIEW_USERS',
      'INVITE_USERS',
      'EDIT_USERS',
      'DELETE_USERS',
      'VIEW_ROLES',
      'CREATE_ROLES',
      'EDIT_ROLES',
      'DELETE_ROLES',
      'VIEW_CUSTOMERS',
      'ADD_CUSTOMERS',
      'EDIT_CUSTOMERS',
      'ARCHIVE_CUSTOMERS',
      'VIEW_SERVICE_LOCATIONS',
      'ADD_SERVICE_LOCATIONS',
      'EDIT_SERVICE_LOCATIONS',
      'CLOSE_SERVICE_LOCATIONS',
      'VIEW_SETTINGS',
      'EDIT_SETTINGS',
      'VIEW_AUDIT_LOGS',
    ];
    return capabilities.includes(capability);
  }),
  useHasAnyCapability: vi.fn((...capabilities: string[]) => {
    const mockCapabilities = [
      'VIEW_USERS',
      'INVITE_USERS',
      'EDIT_USERS',
      'DELETE_USERS',
      'VIEW_ROLES',
      'CREATE_ROLES',
      'EDIT_ROLES',
      'DELETE_ROLES',
      'VIEW_CUSTOMERS',
      'ADD_CUSTOMERS',
      'EDIT_CUSTOMERS',
      'ARCHIVE_CUSTOMERS',
      'VIEW_SERVICE_LOCATIONS',
      'ADD_SERVICE_LOCATIONS',
      'EDIT_SERVICE_LOCATIONS',
      'CLOSE_SERVICE_LOCATIONS',
      'VIEW_SETTINGS',
      'EDIT_SETTINGS',
      'VIEW_AUDIT_LOGS',
    ];
    return capabilities.some(cap => mockCapabilities.includes(cap));
  }),
  useHasAllCapabilities: vi.fn((...capabilities: string[]) => {
    const mockCapabilities = [
      'VIEW_USERS',
      'INVITE_USERS',
      'EDIT_USERS',
      'DELETE_USERS',
      'VIEW_ROLES',
      'CREATE_ROLES',
      'EDIT_ROLES',
      'DELETE_ROLES',
      'VIEW_CUSTOMERS',
      'ADD_CUSTOMERS',
      'EDIT_CUSTOMERS',
      'ARCHIVE_CUSTOMERS',
      'VIEW_SERVICE_LOCATIONS',
      'ADD_SERVICE_LOCATIONS',
      'EDIT_SERVICE_LOCATIONS',
      'CLOSE_SERVICE_LOCATIONS',
      'VIEW_SETTINGS',
      'EDIT_SETTINGS',
      'VIEW_AUDIT_LOGS',
    ];
    return capabilities.every(cap => mockCapabilities.includes(cap));
  }),
}));
